name: Build AbyssVideoDownloader

on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - "**.md"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build AbyssVideoDownloader
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Build AbyssVideoDownloader
        run: ./gradlew build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: abyss-dl
          path: build/libs/abyss-dl.jar
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: ${{ github.ref_name }}
          name: abyss-dl-${{ github.ref_name }}
          files: build/libs/abyss-dl.jar
          draft: true
